SUBSET_NAME_ALLOWED_SYMBOLS = "a-zA-Z0-9_."
DEFAULT_SUBSET_TEMPLATE = "{family}{Variant}"
PRE_CREATE_THUMBNAIL_KEY = "thumbnail_source"


__all__ = (
    "SUBSET_NAME_ALLOWED_SYMBOLS",
    "DEFAULT_SUBSET_TEMPLATE",
    "PRE_CREATE_THUMBNAIL_KEY",
)
