"""
Well-known Traits and Specifications for use in OpenAssetIO hosts and
managers.
"""

# WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

from . import traits
from . import specifications
