# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#

import os
import sys
from pathlib import Path
import re
from Qt.QtWidgets import QApplication


app = QApplication([])

version = {}
openpype_root = Path(os.path.abspath('../..'))
sys.path.insert(0, openpype_root.as_posix())
sys.path.insert(0, (openpype_root / "openpype").as_posix())
sys.path.insert(0, (openpype_root / "igniter").as_posix())
repos = openpype_root / "repos"
repos = [os.path.join(openpype_root, "repos", repo) for repo in repos.as_posix()]
for repo in repos:
    sys.path.append(repo)

with open(openpype_root / "openpype" / "version.py") as fp:
    exec(fp.read(), version)

version_match = re.search(r"(\d+\.\d+.\d+).*", version["__version__"])
openpype_version = version_match.group(1)


todo_include_todos = True
autodoc_mock_imports = ["maya", "pymel", "nuke", "nukestudio", "nukescripts",
                        "hiero", "bpy", "fusion", "houdini", "hou", "unreal",
                        "__builtin__", "resolve", "pysync", "DaVinciResolveScript",
                        "PySide2"]

# -- Project information -----------------------------------------------------

project = 'OpenPype'
copyright = '2019, Orbi Tools'
author = 'Orbi Tools'

# The short X.Y version
version = openpype_version
# The full version, including alpha/beta/rc tags
release = ''


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    # 'sphinx.ext.viewcode',
    'sphinx.ext.autosummary',
    'm2r2',
    'sphinx.ext.inheritance_diagram',
    'autoapi.extension'
]

##############################
# Autoapi settings
##############################

autoapi_dirs = [openpype_root / 'openpype', openpype_root / 'igniter']
autoapi_ignore = [
    "*vendor/*",
    "openpype/vendor/*",
    "openpype/hosts/hiero/api/startup/*",
    "openpype/tools/creator/widgets.py"
]
autoapi_keep_files = True
autoapi_options = [
    'members',
    'undoc-members',
    'show-inheritance',
    'show-module-summary'
]
autoapi_add_toctree_entry = True
autoapi_template_dir = '_autoapi_templates'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'friendly'

# -- Options for autodoc -----------------------------------------------------
autodoc_default_flags = ['members']
autodoc_typehints = 'description'
autosummary_generate = True


# -- Automatically generate API documentation --------------------------------

def run_apidoc(_):

    import shutil
    from sphinx.ext import apidoc

    op_root = os.path.abspath(os.getenv("OPENPYPE_ROOT"))
    os.chdir(op_root)

    conf_dir = str(Path(op_root) / "docs" / "source")
    build_dir = str(Path(op_root) / "docs" / "build")

    if Path(build_dir).exists():
        shutil.rmtree(build_dir)

    builder = ["html"]
    modules = ["igniter", "openpype"]

    ignore_paths = [
        os.path.join(op_root, "vendor"),
        os.path.join(op_root, "openpype", "vendor"),
        os.path.join(op_root, "openpype", "hosts", "hiero", "api", "startup"),
        os.path.join(op_root, "openpype", "tools", "creator", "widgets.py"),
        os.path.join(op_root, "openpype", "vendor", "creator", "widgets.py")
    ]

    for mod in modules:
        argv = [
            "-f",
            "-l",
            "-e",
            "-M",
            "-o", str(Path(os.getenv("OPENPYPE_ROOT")) / "docs" / "source"),
            mod
        ] + ignore_paths

        from sphinx.ext import apidoc
        apidoc.main(argv)


def setup(app):
    app.connect('builder-inited', run_apidoc)

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'collapse_navigation': False,
    'navigation_depth': 5,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'pypedoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'openpype.tex', 'OpenPype Documentation',
     'OrbiTools', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'openpype', 'OpenPype Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'openpype', 'OpenPype Documentation',
     author, 'pype', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'https://docs.python.org/3/': None
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
