//Maya ASCII 2024 scene
//Name: test_project_test_asset_test_task_v002.ma
//Last modified: Tue, Sep 19, 2023 03:32:13 PM
//Codeset: 1252
requires maya "2024";
requires -nodeType "aiOptions" -nodeType "aiAOVDriver" -nodeType "aiAOVFilter" "mtoa" "5.3.0";
requires -nodeType "simpleSelector" -nodeType "renderSetupLayer" -nodeType "renderSetup"
		 -nodeType "collection" "renderSetup.py" "1.0";
requires -nodeType "polyDisc" "modelingToolkit" "0.0.0.0";
requires "stereoCamera" "10.0";
currentUnit -l centimeter -a degree -t pal;
fileInfo "application" "maya";
fileInfo "product" "Maya 2024";
fileInfo "version" "2024";
fileInfo "cutIdentifier" "202302170737-4500172811";
fileInfo "osv" "Windows 10 Pro v2009 (Build: 19045)";
fileInfo "license" "education";
fileInfo "UUID" "EE32580D-4D56-AA7C-A321-50AB519C5D75";
fileInfo "OpenPypeContext" "eyJwdWJsaXNoX2F0dHJpYnV0ZXMiOiB7IlZhbGlkYXRlQ29udGFpbmVycyI6IHsiYWN0aXZlIjogdHJ1ZX19fQ==";
createNode transform -s -n "persp";
	rename -uid "D52C935B-47C9-D868-A875-D799DD17B3A1";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 26.953352922736947 24.362683487437064 26.983403389430531 ;
	setAttr ".r" -type "double3" 1064.7698975365424 54.173034578109736 1075.1660763544442 ;
	setAttr ".rp" -type "double3" -2.0401242849359917e-14 2.2609331405046354e-14 -44.821869662029947 ;
	setAttr ".rpt" -type "double3" -27.999999999999989 -21.000000000000025 16.82186966202995 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "2399E6C0-490F-BA1F-485F-5AA8A01D27BC";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 46.895362757145833;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
	setAttr ".ai_translator" -type "string" "perspective";
createNode transform -s -n "top";
	rename -uid "415C7426-413E-0FAE-FCC3-3DAED7443A52";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" 90 0 0 ;
	setAttr ".rp" -type "double3" 0 0 -1000.1 ;
	setAttr ".rpt" -type "double3" 0 -1000.1 1000.1 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "3BD0CF60-40DB-5278-5D8B-06ACBDA32122";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -s -n "front";
	rename -uid "D83DD5CE-4FE0-AB1B-81B2-87A63F0B7A05";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
	setAttr ".r" -type "double3" 180 0 0 ;
	setAttr ".rp" -type "double3" 0 0 -1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "23313CBA-42C2-0B3A-0FCF-EA965EAC5DEC";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -s -n "side";
	rename -uid "F70F692C-4A0D-BE64-9EE4-A99B6FA2D56E";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 180 -90 0 ;
	setAttr ".rp" -type "double3" 0 0 -1000.1 ;
	setAttr ".rpt" -type "double3" -1000.1 0 1000.1 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "C05669C3-420E-CA11-E5FC-7EB64EF8B632";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
	setAttr ".ai_translator" -type "string" "orthographic";
createNode transform -n "pSphere1_GEO";
	rename -uid "7445A43F-444F-B2D3-4315-2AA013D2E0B6";
	addAttr -ci true -sn "cbId" -ln "cbId" -dt "string";
	setAttr ".cbId" -type "string" "60df31e2be2b48bd3695c056:440654b3dfe4";
createNode mesh -n "pSphere1_GEOShape1" -p "pSphere1_GEO";
	rename -uid "7C731260-45C6-339E-07BF-359446B08EA1";
	addAttr -ci true -sn "cbId" -ln "cbId" -dt "string";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Ambient+Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".ndt" 0;
	setAttr ".cbId" -type "string" "60df31e2be2b48bd3695c056:bf8e49bb98ec";
createNode transform -n "pDisc1";
	rename -uid "DED70CCF-4C19-16E4-9E5D-66A05037BA47";
	addAttr -ci true -sn "cbId" -ln "cbId" -dt "string";
	setAttr ".cbId" -type "string" "60df31e2be2b48bd3695c056:90e762703f08";
createNode mesh -n "pDiscShape1" -p "pDisc1";
	rename -uid "E1FCDCCF-4DE1-D3B9-C4F8-3285F1CF5B25";
	addAttr -ci true -sn "cbId" -ln "cbId" -dt "string";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Ambient+Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".ndt" 0;
	setAttr ".ai_translator" -type "string" "polymesh";
	setAttr ".cbId" -type "string" "60df31e2be2b48bd3695c056:4ee3da11a1a4";
createNode transform -n "persp1";
	rename -uid "292F1351-4E41-A890-D6D5-A5A4F7D94C76";
	setAttr ".t" -type "double3" 3.7889010960863949 2.8416759114717678 3.7889010364817537 ;
	setAttr ".r" -type "double3" -27.938352729602379 44.999999999999972 -5.172681101354183e-14 ;
createNode camera -n "perspShape1" -p "persp1";
	rename -uid "9277418C-43C8-5064-A7C6-64AC829A76F2";
	setAttr -k off ".v";
	setAttr ".ovr" 1.3;
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 6.0652013012246453;
	setAttr ".imn" -type "string" "persp1";
	setAttr ".den" -type "string" "persp1_depth";
	setAttr ".man" -type "string" "persp1_mask";
	setAttr ".tp" -type "double3" -1.1920928955078125e-07 0 -1.7881393432617188e-07 ;
	setAttr ".hc" -type "string" "viewSet -p %camera";
	setAttr ".dr" yes;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "DE23EE64-42DE-81CD-D647-7BBB19BCBFA3";
	setAttr -s 2 ".lnk";
	setAttr -s 2 ".slnk";
createNode shapeEditorManager -n "shapeEditorManager";
	rename -uid "BD03B23E-4D67-AF2D-851B-A9ABC29B43C4";
createNode poseInterpolatorManager -n "poseInterpolatorManager";
	rename -uid "84F2093C-4C3A-51D2-E808-8F9C285E6515";
createNode displayLayerManager -n "layerManager";
	rename -uid "358B01A7-4863-7070-F637-AC888D0F48F4";
createNode displayLayer -n "defaultLayer";
	rename -uid "4A776D1B-401F-7069-1C74-A7AAE84CEE03";
	setAttr ".ufem" -type "stringArray" 0  ;
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "5401FA40-4494-5536-F0B8-A6AC42B548AF";
	setAttr -s 2 ".rlmi[1]"  1;
	setAttr -s 2 ".rlmi";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "B134920D-4508-23BD-A6CA-11B43DE03F53";
	setAttr ".g" yes;
createNode renderSetup -n "renderSetup";
	rename -uid "9A8F0D15-41AB-CA70-C2D8-B78840BF9BC1";
createNode polySphere -n "polySphere1";
	rename -uid "DA319706-4ACF-B15C-53B2-48AC80D202EA";
createNode objectSet -n "modelMain";
	rename -uid "A76AD4F8-4CF5-AA0D-4E98-BABEE6454CC3";
	addAttr -ci true -sn "cbId" -ln "cbId" -dt "string";
	addAttr -ci true -sn "id" -ln "id" -dt "string";
	addAttr -ci true -sn "family" -ln "family" -dt "string";
	addAttr -ci true -sn "subset" -ln "subset" -dt "string";
	addAttr -ci true -sn "active" -ln "active" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "creator_identifier" -ln "creator_identifier" -dt "string";
	addAttr -ci true -sn "variant" -ln "variant" -dt "string";
	addAttr -ci true -sn "asset" -ln "asset" -dt "string";
	addAttr -ci true -sn "task" -ln "task" -dt "string";
	addAttr -ci true -sn "instance_id" -ln "instance_id" -dt "string";
	addAttr -ci true -sn "writeColorSets" -ln "writeColorSets" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "writeFaceSets" -ln "writeFaceSets" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "includeParentHierarchy" -ln "includeParentHierarchy" -min 
		0 -max 1 -at "bool";
	addAttr -ci true -sn "attr" -ln "attr" -dt "string";
	addAttr -ci true -sn "attrPrefix" -ln "attrPrefix" -dt "string";
	addAttr -ci true -sn "publish_attributes" -ln "publish_attributes" -dt "string";
	addAttr -ci true -sn "__creator_attributes_keys" -ln "__creator_attributes_keys" 
		-dt "string";
	setAttr ".ihi" 0;
	setAttr ".cbId" -type "string" "60df31e2be2b48bd3695c056:7364ea6776c9";
	setAttr ".id" -type "string" "pyblish.avalon.instance";
	setAttr ".family" -type "string" "model";
	setAttr ".subset" -type "string" "modelMain";
	setAttr -cb on ".active" yes;
	setAttr ".creator_identifier" -type "string" "io.openpype.creators.maya.model";
	setAttr ".variant" -type "string" "Main";
	setAttr ".asset" -type "string" "test_asset";
	setAttr ".task" -type "string" "test_task";
	setAttr ".instance_id" -type "string" "6889d3db-b813-43db-96de-9ba555dc4472";
	setAttr -cb on ".writeColorSets";
	setAttr -cb on ".writeFaceSets";
	setAttr -cb on ".includeParentHierarchy";
	setAttr ".attr" -type "string" "";
	setAttr ".attrPrefix" -type "string" "";
	setAttr ".publish_attributes" -type "string" "{\"ValidateNodeIDsRelated\": {\"active\": true}, \"ValidateTransformNamingSuffix\": {\"active\": true}, \"ValidateColorSets\": {\"active\": true}, \"ValidateMeshArnoldAttributes\": {\"active\": true}, \"ValidateMeshHasUVs\": {\"active\": true}, \"ValidateMeshNonZeroEdgeLength\": {\"active\": true}, \"ExtractModel\": {\"active\": true}}";
	setAttr ".__creator_attributes_keys" -type "string" "writeColorSets,writeFaceSets,includeParentHierarchy,attr,attrPrefix";
createNode script -n "uiConfigurationScriptNode";
	rename -uid "4B7AFB53-452E-E870-63E1-CCA1DD6EAF13";
	setAttr ".b" -type "string" "// Maya Mel UI Configuration File.\n// No UI generated in batch mode.\n";
	setAttr ".st" 3;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "72B19BC2-43A2-E229-0A73-2CB861A291D1";
	setAttr ".b" -type "string" "playbackOptions -min 1000 -max 1001 -ast 1000 -aet 1001 ";
	setAttr ".st" 6;
createNode polyDisc -n "polyDisc1";
	rename -uid "9ED8A7BD-4FFD-6107-4322-35ACD1D3AC42";
createNode aiOptions -s -n "defaultArnoldRenderOptions";
	rename -uid "51BB3D7A-4C7D-FCDD-1B21-D89934107F98";
	setAttr ".skip_license_check" yes;
createNode aiAOVFilter -s -n "defaultArnoldFilter";
	rename -uid "989A5992-46C8-0CB2-B2B8-4E868F31FEA8";
	setAttr ".ai_translator" -type "string" "gaussian";
createNode aiAOVDriver -s -n "defaultArnoldDriver";
	rename -uid "B8469AD8-47C8-9EF1-FE5E-5AB50ABC1536";
	setAttr ".merge_AOVs" yes;
	setAttr ".ai_translator" -type "string" "exr";
createNode aiAOVDriver -s -n "defaultArnoldDisplayDriver";
	rename -uid "21D4F4CD-4D78-001C-610D-798402CD7CF0";
	setAttr ".output_mode" 0;
	setAttr ".ai_translator" -type "string" "maya";
createNode objectSet -n "workfileMain";
	rename -uid "3C9B5D6F-4579-8E3B-5B7D-4C88865A1C68";
	addAttr -ci true -sn "cbId" -ln "cbId" -dt "string";
	addAttr -ci true -sn "id" -ln "id" -dt "string";
	addAttr -ci true -sn "family" -ln "family" -dt "string";
	addAttr -ci true -sn "subset" -ln "subset" -dt "string";
	addAttr -ci true -sn "active" -ln "active" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "creator_identifier" -ln "creator_identifier" -dt "string";
	addAttr -ci true -sn "variant" -ln "variant" -dt "string";
	addAttr -ci true -sn "asset" -ln "asset" -dt "string";
	addAttr -ci true -sn "task" -ln "task" -dt "string";
	addAttr -ci true -sn "instance_id" -ln "instance_id" -dt "string";
	addAttr -ci true -sn "publish_attributes" -ln "publish_attributes" -dt "string";
	addAttr -ci true -sn "__creator_attributes_keys" -ln "__creator_attributes_keys" 
		-dt "string";
	setAttr ".ihi" 0;
	setAttr ".hio" yes;
	setAttr ".cbId" -type "string" "60df31e2be2b48bd3695c056:30d256dac64c";
	setAttr ".id" -type "string" "pyblish.avalon.instance";
	setAttr ".family" -type "string" "workfile";
	setAttr ".subset" -type "string" "workfileTest_task";
	setAttr -cb on ".active" yes;
	setAttr ".creator_identifier" -type "string" "io.openpype.creators.maya.workfile";
	setAttr ".variant" -type "string" "Main";
	setAttr ".asset" -type "string" "test_asset";
	setAttr ".task" -type "string" "test_task";
	setAttr ".instance_id" -type "string" "911dc92a-ad29-41e5-bbf9-733d56174fb9";
	setAttr ".publish_attributes" -type "string" "{\"ExtractImportReference\": {\"active\": false}}";
	setAttr ".__creator_attributes_keys" -type "string" "";
createNode objectSet -n "renderingMain";
	rename -uid "8A999C2F-4922-B15D-8D5C-45A16465B69F";
	addAttr -ci true -sn "pre_creator_identifier" -ln "pre_creator_identifier" -dt "string";
	addAttr -ci true -sn "cbId" -ln "cbId" -dt "string";
	setAttr ".ihi" 0;
	setAttr ".pre_creator_identifier" -type "string" "io.openpype.creators.maya.renderlayer";
	setAttr ".cbId" -type "string" "60df31e2be2b48bd3695c056:042447475732";
createNode renderSetupLayer -n "Main";
	rename -uid "2202E438-4CEF-F64E-737C-F48C65E31126";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode renderLayer -n "rs_Main";
	rename -uid "DF0259B1-4F96-DA7E-C74F-B599FBE15C18";
	setAttr ".do" 1;
createNode collection -n "defaultCollection";
	rename -uid "E5014237-4DA9-6FC0-633D-69AFA56161B3";
	addAttr -ci true -sn "es" -ln "expandedState" -min 0 -max 1 -at "bool";
	setAttr ".es" yes;
createNode simpleSelector -n "defaultCollectionSelector";
	rename -uid "7CA2F6D8-483C-B020-BC03-EF9563A52163";
	setAttr ".pat" -type "string" "*";
createNode objectSet -n "_renderingMain:Main";
	rename -uid "1EEC3A3B-49CF-0C79-5340-39805174FB8A";
	addAttr -s false -ci true -sn "renderlayer" -ln "renderlayer" -at "message";
	addAttr -ci true -sn "id" -ln "id" -dt "string";
	addAttr -ci true -sn "family" -ln "family" -dt "string";
	addAttr -ci true -sn "subset" -ln "subset" -dt "string";
	addAttr -ci true -sn "active" -ln "active" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "creator_identifier" -ln "creator_identifier" -dt "string";
	addAttr -ci true -sn "variant" -ln "variant" -dt "string";
	addAttr -ci true -sn "asset" -ln "asset" -dt "string";
	addAttr -ci true -sn "task" -ln "task" -dt "string";
	addAttr -ci true -sn "instance_id" -ln "instance_id" -dt "string";
	addAttr -ci true -sn "review" -ln "review" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "extendFrames" -ln "extendFrames" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "overrideExistingFrame" -ln "overrideExistingFrame" -min 0 
		-max 1 -at "bool";
	addAttr -ci true -sn "tileRendering" -ln "tileRendering" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "tilesX" -ln "tilesX" -at "long";
	addAttr -ci true -sn "tilesY" -ln "tilesY" -at "long";
	addAttr -ci true -sn "convertToScanline" -ln "convertToScanline" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "useReferencedAovs" -ln "useReferencedAovs" -min 0 -max 1 -at "bool";
	addAttr -ci true -sn "renderSetupIncludeLights" -ln "renderSetupIncludeLights" -min 
		0 -max 1 -at "bool";
	addAttr -ci true -sn "publish_attributes" -ln "publish_attributes" -dt "string";
	addAttr -ci true -sn "__creator_attributes_keys" -ln "__creator_attributes_keys" 
		-dt "string";
	addAttr -ci true -sn "cbId" -ln "cbId" -dt "string";
	setAttr ".ihi" 0;
	setAttr ".id" -type "string" "pyblish.avalon.instance";
	setAttr ".family" -type "string" "renderlayer";
	setAttr ".subset" -type "string" "renderMain";
	setAttr -cb on ".active" yes;
	setAttr ".creator_identifier" -type "string" "io.openpype.creators.maya.renderlayer";
	setAttr ".variant" -type "string" "Main";
	setAttr ".asset" -type "string" "test_asset";
	setAttr ".task" -type "string" "test_task";
	setAttr ".instance_id" -type "string" "8a9cfb85-9602-4e5e-a4bc-27a2986bae7f";
	setAttr -cb on ".review" yes;
	setAttr -cb on ".extendFrames";
	setAttr -cb on ".overrideExistingFrame" yes;
	setAttr -cb on ".tileRendering";
	setAttr -cb on ".tilesX" 2;
	setAttr -cb on ".tilesY" 2;
	setAttr -cb on ".convertToScanline";
	setAttr -cb on ".useReferencedAovs";
	setAttr -cb on ".renderSetupIncludeLights" yes;
	setAttr ".publish_attributes" -type "string" "{\"CollectDeadlinePools\": {\"primaryPool\": \"\", \"secondaryPool\": \"\"}, \"ValidateDeadlinePools\": {\"active\": true}, \"ValidateFrameRange\": {\"active\": true}, \"ExtractImportReference\": {\"active\": false}, \"MayaSubmitDeadline\": {\"priority\": 50, \"chunkSize\": 1, \"machineList\": \"\", \"whitelist\": false, \"tile_priority\": 50, \"strict_error_checking\": true}, \"ProcessSubmittedJobOnFarm\": {\"publishJobState\": \"Active\"}}";
	setAttr ".__creator_attributes_keys" -type "string" "review,extendFrames,overrideExistingFrame,tileRendering,tilesX,tilesY,convertToScanline,useReferencedAovs,renderSetupIncludeLights";
	setAttr ".cbId" -type "string" "60df31e2be2b48bd3695c056:69960f336351";
select -ne :time1;
	setAttr ".o" 1001;
	setAttr ".unw" 1001;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".dli" 1;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 1;
select -ne :renderPartition;
	setAttr -s 2 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 5 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
	setAttr -s 2 ".r";
select -ne :standardSurface1;
	setAttr ".b" 0.80000001192092896;
	setAttr ".bc" -type "float3" 1 1 1 ;
	setAttr ".s" 0.20000000298023224;
	setAttr ".sr" 0.40000000596046448;
select -ne :initialShadingGroup;
	setAttr -s 2 ".dsm";
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr ".ren" -type "string" "arnold";
	setAttr ".outf" 51;
	setAttr ".imfkey" -type "string" "exr";
	setAttr ".an" yes;
	setAttr ".fs" 1001;
	setAttr ".ef" 1001;
	setAttr ".oft" -type "string" "";
	setAttr ".pff" yes;
	setAttr ".ifp" -type "string" "<Scene>/<RenderLayer>/<RenderLayer>";
	setAttr ".rv" -type "string" "";
	setAttr ".pram" -type "string" "";
	setAttr ".poam" -type "string" "";
	setAttr ".prlm" -type "string" "";
	setAttr ".polm" -type "string" "";
	setAttr ".prm" -type "string" "";
	setAttr ".pom" -type "string" "";
	setAttr ".dss" -type "string" "lambert1";
select -ne :defaultResolution;
	setAttr ".w" 10;
	setAttr ".h" 6;
	setAttr ".pa" 1;
	setAttr ".al" yes;
	setAttr ".dar" 1.6666666269302368;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya-legacy/config.ocio";
	setAttr ".vtn" -type "string" "sRGB gamma (legacy)";
	setAttr ".vn" -type "string" "sRGB gamma";
	setAttr ".dn" -type "string" "legacy";
	setAttr ".wsn" -type "string" "scene-linear Rec 709/sRGB";
	setAttr ".ovt" no;
	setAttr ".povt" no;
	setAttr ".otn" -type "string" "sRGB gamma (legacy)";
	setAttr ".potn" -type "string" "sRGB gamma (legacy)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr "rs_Main.ri" ":persp.rlio[0]";
connectAttr "rs_Main.ri" ":top.rlio[0]";
connectAttr "rs_Main.ri" ":front.rlio[0]";
connectAttr "rs_Main.ri" ":side.rlio[0]";
connectAttr "rs_Main.ri" "pSphere1_GEO.rlio[0]";
connectAttr "polySphere1.out" "pSphere1_GEOShape1.i";
connectAttr "rs_Main.ri" "pDisc1.rlio[0]";
connectAttr "polyDisc1.output" "pDiscShape1.i";
connectAttr "rs_Main.ri" "persp1.rlio[0]";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "Main.msg" "renderSetup.frl";
connectAttr "Main.msg" "renderSetup.lrl";
connectAttr "pSphere1_GEO.iog" "modelMain.dsm" -na;
connectAttr ":defaultArnoldDisplayDriver.msg" ":defaultArnoldRenderOptions.drivers"
		 -na;
connectAttr ":defaultArnoldFilter.msg" ":defaultArnoldRenderOptions.filt";
connectAttr ":defaultArnoldDriver.msg" ":defaultArnoldRenderOptions.drvr";
connectAttr "_renderingMain:Main.msg" "renderingMain.dnsm" -na;
connectAttr "rs_Main.msg" "Main.lrl";
connectAttr "renderSetup.lit" "Main.pls";
connectAttr "defaultCollection.msg" "Main.cl";
connectAttr "defaultCollection.msg" "Main.ch";
connectAttr "renderLayerManager.rlmi[1]" "rs_Main.rlid";
connectAttr "defaultCollectionSelector.c" "defaultCollection.sel";
connectAttr "Main.lit" "defaultCollection.pls";
connectAttr "Main.nic" "defaultCollection.pic";
connectAttr "Main.msg" "_renderingMain:Main.renderlayer";
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
connectAttr "rs_Main.msg" ":defaultRenderingList1.r" -na;
connectAttr "pSphere1_GEOShape1.iog" ":initialShadingGroup.dsm" -na;
connectAttr "pDiscShape1.iog" ":initialShadingGroup.dsm" -na;
// End of test_project_test_asset_test_task_v002.ma
