"""
Specifications defined in the 'openassetio-mediacreation' package.
"""

# WARNING: This file is auto-generated by openassetio-traitgen, do not edit.

from . import application
from . import audio
from . import lifecycle
from . import representation
from . import threeDimensional
from . import twoDimensional
